<!doctype html>
<html>
<head>
    {% block title %}
    {% endblock %}

    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <meta name="viewport" content="width=device-width, user-scalable=no">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
    {% endblock %}
    {% block metaExt %}
    {% endblock %}

    {% block head %}
    {% endblock %}
</head>
<body>
{% block body %}
{% endblock %}

{% block footer %}
{% endblock %}
</body>
</html>